language: java
install: true
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - mkdir db
  - ls
  - mongod --dbpath db --fork --logpath mongodb.log
  - sleep 15

script: 
  - mvn clean verify
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)